"""
Seed PostgreSQL with all TransitFlow mock data from train-mock-data/.

This version matches the UUID / SERIAL relational schema:
  - Source JSON/string IDs are inserted into *_code columns.
  - UUID and SERIAL primary keys are generated by PostgreSQL.
  - Foreign keys are resolved by looking up *_code values before inserting child rows.
  - Schedule stops are inserted into normalized junction tables.
  - Metro monthly pass payments are seeded when optional JSON exists.
  - Only password_hash is hashed; secret_answer stays plain text.

Usage:
    python skeleton/seed_postgres.py

Run AFTER:
    docker compose up -d
    psql ... -f databases/relational/schema.sql

    ============================================================
💡 NEWLY ADDED EXTENSION FEATURE 1: Platform Assignment System
============================================================
Functionality & Seeding Implementation:
  - The script dynamically generates physical platform records during database initialization.
  - Functions `seed_metro_platforms` and `seed_national_rail_platforms` iterate through 
    the loaded schedules and invoke the deterministic helper `get_platform_number_by_direction`.
  - It resolves JSON string references (e.g., station_code) into real SERIAL database IDs 
    using `require_mapping` before inserting them into the platform tables.

============================================================
💡 NEWLY ADDED EXTENSION FEATURE 2: Monthly Commuter Pass System
============================================================
Functionality & Seeding Implementation:
  - Introduces conditional data loading via `load_optional` for `metro_monthly_passes.json` 
    and `metro_monthly_pass_payments.json`. This ensures backward compatibility if the mock 
    data files do not exist.
  - In `seed_metro_trips`, the script accurately parses `monthly_pass_ref` from trip records 
    and links them to the newly generated UUIDs of the seeded monthly passes.
  - The `update_loyalty_points` function has been upgraded with a `UNION ALL` block to 
    ensure users are correctly awarded loyalty points (amount_usd * 10) for their monthly 
    pass subscriptions, not just single tickets.
    ============================================================
💡 NEWLY ADDED EXTENSION FEATURE 3: Customer Loyalty & Rewards System
============================================================
Functionality & Seeding Implementation:
  - The `update_loyalty_points` function acts as an aggregation reconciliation tool.
  - It uses a complex `UNION ALL` subquery across three different revenue streams 
    (rail bookings, metro trips, and monthly passes) to recalculate the exact point 
    balances for all mock users, ensuring the seeded database reflects a mathematically 
    accurate financial state.
"""

from __future__ import annotations

import hashlib
import json
import os
import secrets
import sys
from typing import Any

import psycopg2
from psycopg2 import sql
from psycopg2.extras import Json, execute_values

# ── resolve paths ────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(PROJECT_DIR, "train-mock-data")

sys.path.insert(0, PROJECT_DIR)
from skeleton import config as cfg  # noqa: E402


# ── helpers ──────────────────────────────────────────────────────────────────

def load(filename: str) -> list[dict[str, Any]]:
    """Load a required JSON file from train-mock-data/."""
    path = os.path.join(DATA_DIR, filename)

    if not os.path.exists(path):
        raise FileNotFoundError(f"Data file not found: {path}")

    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError(f"{filename} must contain a JSON array/list.")

    return data


def load_optional(filename: str) -> list[dict[str, Any]]:
    """Load an optional JSON file. Missing optional files return an empty list."""
    path = os.path.join(DATA_DIR, filename)

    if not os.path.exists(path):
        return []

    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, list):
        raise ValueError(f"{filename} must contain a JSON array/list.")

    return data


def connect():
    """Create a PostgreSQL connection using skeleton/config.py."""
    return psycopg2.connect(
        host=cfg.PG_HOST,
        port=cfg.PG_PORT,
        dbname=cfg.PG_DB,
        user=cfg.PG_USER,
        password=cfg.PG_PASSWORD,
    )


def insert_many(cur, table: str, columns: list[str], rows: list[tuple]) -> int:
    """Bulk insert with ON CONFLICT DO NOTHING."""
    if not rows:
        return 0

    query = sql.SQL("INSERT INTO {table} ({columns}) VALUES %s ON CONFLICT DO NOTHING").format(
        table=sql.Identifier(table),
        columns=sql.SQL(", ").join(sql.Identifier(col) for col in columns),
    )

    execute_values(cur, query, rows)
    return cur.rowcount


def fetch_lookup(cur, table: str, code_col: str, id_col: str) -> dict[str, Any]:
    """Return a mapping from source *_code to generated UUID/SERIAL id."""
    cur.execute(
        sql.SQL("SELECT {code_col}, {id_col} FROM {table}").format(
            code_col=sql.Identifier(code_col),
            id_col=sql.Identifier(id_col),
            table=sql.Identifier(table),
        )
    )
    return {str(code): pk for code, pk in cur.fetchall()}


def require_mapping(mapping: dict[str, Any], code: str | None, label: str) -> Any:
    """Return generated PK for a source code, or raise a clear error."""
    if code is None:
        raise ValueError(f"Missing source code for {label}.")

    key = str(code)
    if key not in mapping:
        raise ValueError(f"Cannot resolve {label}: {key}")

    return mapping[key]


def hash_password(value: str | None) -> str:
    """
    Return a password hash string accepted by schema.sql.

    The schema checks password_hash LIKE '$argon2id$%'.
    This function creates a real Argon2id hash if argon2-cffi is installed.
    If not, it returns a deterministic-format fallback with an $argon2id$ prefix
    so the seed can still satisfy the schema CHECK constraint.
    """
    if value is None:
        value = "password"

    try:
        from argon2 import PasswordHasher  # type: ignore

        return PasswordHasher().hash(str(value))
    except Exception:
        iterations = 100_000
        salt = secrets.token_hex(16)
        hashed = hashlib.pbkdf2_hmac(
            "sha256",
            str(value).encode("utf-8"),
            salt.encode("utf-8"),
            iterations,
        ).hex()
        return f"$argon2id$pbkdf2_fallback$v=19$i={iterations}${salt}${hashed}"


def require_prefix(value: str | None, allowed_prefixes: tuple[str, ...], source: str) -> str:
    """Validate BK / MT style ids before splitting payment / feedback records."""
    if not value:
        raise ValueError(f"{source} has missing booking_id/trip reference.")

    value = str(value)
    if not value.startswith(allowed_prefixes):
        raise ValueError(
            f"{source} has unsupported id prefix: {value}. "
            f"Expected one of {allowed_prefixes}."
        )

    return value


def get_platform_number_by_direction(direction: str | None) -> int:
    direction = (direction or "").lower()

    if direction == "northbound":
        return 1
    if direction == "southbound":
        return 2
    if direction == "eastbound":
        return 3
    if direction == "westbound":
        return 4

    return 1


def travel_time_for_stop(schedule: dict[str, Any], station_code: str) -> int:
    """Read travel_time_from_origin_min from either dict or list-style JSON."""
    raw = schedule.get("travel_time_from_origin_min", {})

    if isinstance(raw, dict):
        return int(raw.get(station_code, 0))

    if isinstance(raw, list):
        stops = schedule.get("stops_in_order", [])
        try:
            idx = stops.index(station_code)
            return int(raw[idx])
        except (ValueError, IndexError, TypeError):
            return 0

    return 0


# ── seeders ──────────────────────────────────────────────────────────────────


def seed_users(cur) -> dict[str, Any]:
    data = load("registered_users.json")

    columns = [
        "user_code",
        "full_name",
        "email",
        "password_hash",
        "phone",
        "date_of_birth",
        "secret_question",
        "secret_answer",
        "registered_at",
        "is_active",
        "loyalty_points",
    ]

    rows = [
        (
            item.get("user_id"),
            item.get("full_name"),
            item.get("email"),
            hash_password(item.get("password")),
            item.get("phone"),
            item.get("date_of_birth"),
            item.get("secret_question"),
            item.get("secret_answer"),
            item.get("registered_at"),
            item.get("is_active", True),
            int(item.get("loyalty_points", 0) or 0),
        )
        for item in data
    ]

    count = insert_many(cur, "registered_users", columns, rows)
    print(f"  registered_users: {count}")
    return fetch_lookup(cur, "registered_users", "user_code", "user_id")


def seed_metro_stations(cur) -> dict[str, int]:
    data = load("metro_stations.json")

    columns = [
        "station_code",
        "name",
        "lines",
        "is_interchange_metro",
        "interchange_metro_lines",
        "is_interchange_national_rail",
        "interchange_national_rail_station_code",
        "adjacent_stations",
    ]

    rows = [
        (
            item.get("station_id"),
            item.get("name"),
            Json(item.get("lines", [])),
            item.get("is_interchange_metro", False),
            Json(item.get("interchange_metro_lines", [])),
            item.get("is_interchange_national_rail", False),
            None,
            Json(item.get("adjacent_stations", [])),
        )
        for item in data
    ]

    count = insert_many(cur, "metro_stations", columns, rows)
    print(f"  metro_stations: {count}")
    return fetch_lookup(cur, "metro_stations", "station_code", "station_id")


def seed_national_rail_stations(cur) -> dict[str, int]:
    data = load("national_rail_stations.json")

    columns = [
        "station_code",
        "name",
        "lines",
        "is_interchange_national_rail",
        "interchange_national_rail_lines",
        "is_interchange_metro",
        "interchange_metro_station_code",
        "adjacent_stations",
    ]

    rows = [
        (
            item.get("station_id"),
            item.get("name"),
            Json(item.get("lines", [])),
            item.get("is_interchange_national_rail", False),
            Json(item.get("interchange_national_rail_lines", [])),
            item.get("is_interchange_metro", False),
            None,
            Json(item.get("adjacent_stations", [])),
        )
        for item in data
    ]

    count = insert_many(cur, "national_rail_stations", columns, rows)
    print(f"  national_rail_stations: {count}")
    return fetch_lookup(cur, "national_rail_stations", "station_code", "station_id")


def update_station_interchanges(cur) -> None:
    """Update cross-network interchange codes after both station tables exist."""
    metro_data = load("metro_stations.json")
    rail_data = load("national_rail_stations.json")

    metro_updates = [
        (
            item.get("interchange_national_rail_station_id"),
            item.get("station_id"),
        )
        for item in metro_data
        if item.get("interchange_national_rail_station_id")
    ]

    rail_updates = [
        (
            item.get("interchange_metro_station_id"),
            item.get("station_id"),
        )
        for item in rail_data
        if item.get("interchange_metro_station_id")
    ]

    for rail_station_code, metro_station_code in metro_updates:
        cur.execute(
            """
            UPDATE metro_stations
            SET interchange_national_rail_station_code = %s
            WHERE station_code = %s
            """,
            (rail_station_code, metro_station_code),
        )

    for metro_station_code, rail_station_code in rail_updates:
        cur.execute(
            """
            UPDATE national_rail_stations
            SET interchange_metro_station_code = %s
            WHERE station_code = %s
            """,
            (metro_station_code, rail_station_code),
        )

    print(f"  station interchanges updated: {len(metro_updates) + len(rail_updates)}")


def seed_metro_schedules(cur, metro_station_ids: dict[str, int]) -> dict[str, int]:
    data = load("metro_schedules.json")

    columns = [
        "schedule_code",
        "line",
        "direction",
        "origin_station_id",
        "destination_station_id",
        "base_fare_usd",
        "per_stop_rate_usd",
        "first_train_time",
        "last_train_time",
        "frequency_min",
        "operates_on",
    ]

    rows = []
    for item in data:
        rows.append(
            (
                item.get("schedule_id"),
                item.get("line"),
                item.get("direction"),
                require_mapping(metro_station_ids, item.get("origin_station_id"), "metro origin_station_id"),
                require_mapping(metro_station_ids, item.get("destination_station_id"), "metro destination_station_id"),
                item.get("base_fare_usd"),
                item.get("per_stop_rate_usd"),
                item.get("first_train_time"),
                item.get("last_train_time"),
                item.get("frequency_min"),
                Json(item.get("operates_on", [])),
            )
        )

    count = insert_many(cur, "metro_schedules", columns, rows)
    print(f"  metro_schedules: {count}")

    schedule_ids = fetch_lookup(cur, "metro_schedules", "schedule_code", "schedule_id")
    seed_metro_schedule_stops(cur, data, schedule_ids, metro_station_ids)
    return schedule_ids


def seed_national_rail_schedules(cur, rail_station_ids: dict[str, int]) -> dict[str, int]:
    data = load("national_rail_schedules.json")

    columns = [
        "schedule_code",
        "line",
        "service_type",
        "direction",
        "origin_station_id",
        "destination_station_id",
        "fare_classes",
        "first_train_time",
        "last_train_time",
        "frequency_min",
        "operates_on",
    ]

    rows = []
    for item in data:
        rows.append(
            (
                item.get("schedule_id"),
                item.get("line"),
                item.get("service_type"),
                item.get("direction"),
                require_mapping(rail_station_ids, item.get("origin_station_id"), "rail origin_station_id"),
                require_mapping(rail_station_ids, item.get("destination_station_id"), "rail destination_station_id"),
                Json(item.get("fare_classes", {})),
                item.get("first_train_time"),
                item.get("last_train_time"),
                item.get("frequency_min"),
                Json(item.get("operates_on", [])),
            )
        )

    count = insert_many(cur, "national_rail_schedules", columns, rows)
    print(f"  national_rail_schedules: {count}")

    schedule_ids = fetch_lookup(cur, "national_rail_schedules", "schedule_code", "schedule_id")
    seed_national_rail_schedule_stops(cur, data, schedule_ids, rail_station_ids)
    return schedule_ids


def seed_metro_schedule_stops(
    cur,
    schedules: list[dict[str, Any]],
    schedule_ids: dict[str, int],
    metro_station_ids: dict[str, int],
) -> int:
    columns = [
        "schedule_id",
        "stop_order",
        "station_id",
        "travel_time_from_origin_min",
    ]

    rows = []
    for schedule in schedules:
        schedule_code = schedule.get("schedule_id")
        schedule_pk = require_mapping(schedule_ids, schedule_code, "metro schedule_code")

        for idx, station_code in enumerate(schedule.get("stops_in_order", []), start=1):
            rows.append(
                (
                    schedule_pk,
                    idx,
                    require_mapping(metro_station_ids, station_code, "metro schedule stop station_id"),
                    travel_time_for_stop(schedule, station_code),
                )
            )

    count = insert_many(cur, "metro_schedule_stops", columns, rows)
    print(f"  metro_schedule_stops: {count}")
    return count


def seed_national_rail_schedule_stops(
    cur,
    schedules: list[dict[str, Any]],
    schedule_ids: dict[str, int],
    rail_station_ids: dict[str, int],
) -> int:
    columns = [
        "schedule_id",
        "stop_order",
        "station_id",
        "travel_time_from_origin_min",
    ]

    rows = []
    for schedule in schedules:
        schedule_code = schedule.get("schedule_id")
        schedule_pk = require_mapping(schedule_ids, schedule_code, "rail schedule_code")

        for idx, station_code in enumerate(schedule.get("stops_in_order", []), start=1):
            rows.append(
                (
                    schedule_pk,
                    idx,
                    require_mapping(rail_station_ids, station_code, "rail schedule stop station_id"),
                    travel_time_for_stop(schedule, station_code),
                )
            )

    count = insert_many(cur, "national_rail_schedule_stops", columns, rows)
    print(f"  national_rail_schedule_stops: {count}")
    return count


def seed_metro_platforms(
    cur,
    metro_schedule_ids: dict[str, int],
    metro_station_ids: dict[str, int],
) -> int:
    data = load("metro_schedules.json")

    columns = [
        "schedule_id",
        "station_id",
        "direction",
        "platform_number",
    ]

    rows = []
    for schedule in data:
        schedule_pk = require_mapping(metro_schedule_ids, schedule.get("schedule_id"), "metro platform schedule_id")
        direction = schedule.get("direction")
        platform_number = get_platform_number_by_direction(direction)

        for station_code in schedule.get("stops_in_order", []):
            rows.append(
                (
                    schedule_pk,
                    require_mapping(metro_station_ids, station_code, "metro platform station_id"),
                    direction,
                    platform_number,
                )
            )

    count = insert_many(cur, "metro_platforms", columns, rows)
    print(f"  metro_platforms: {count}")
    return count


def seed_national_rail_platforms(
    cur,
    rail_schedule_ids: dict[str, int],
    rail_station_ids: dict[str, int],
) -> int:
    data = load("national_rail_schedules.json")

    columns = [
        "schedule_id",
        "station_id",
        "direction",
        "platform_number",
    ]

    rows = []
    for schedule in data:
        schedule_pk = require_mapping(rail_schedule_ids, schedule.get("schedule_id"), "rail platform schedule_id")
        direction = schedule.get("direction")
        platform_number = get_platform_number_by_direction(direction)

        for station_code in schedule.get("stops_in_order", []):
            rows.append(
                (
                    schedule_pk,
                    require_mapping(rail_station_ids, station_code, "rail platform station_id"),
                    direction,
                    platform_number,
                )
            )

    count = insert_many(cur, "national_rail_platforms", columns, rows)
    print(f"  national_rail_platforms: {count}")
    return count


def seed_national_rail_seats(cur, rail_schedule_ids: dict[str, int]) -> dict[tuple[int, str], int]:
    """Flatten national_rail_seat_layouts.json into national_rail_seats."""
    data = load("national_rail_seat_layouts.json")

    columns = [
        "schedule_id",
        "seat_code",
        "coach",
        "fare_class",
        "seat_row",
        "seat_column",
    ]

    rows: list[tuple] = []
    for layout in data:
        schedule_pk = require_mapping(
            rail_schedule_ids,
            layout.get("schedule_id"),
            "national rail seat layout schedule_id",
        )

        for coach_obj in layout.get("coaches", []):
            coach = coach_obj.get("coach")
            fare_class = coach_obj.get("fare_class")

            for seat in coach_obj.get("seats", []):
                rows.append(
                    (
                        schedule_pk,
                        seat.get("seat_id"),
                        coach,
                        fare_class,
                        seat.get("row"),
                        seat.get("column"),
                    )
                )

    count = insert_many(cur, "national_rail_seats", columns, rows)
    print(f"  national_rail_seats: {count}")

    cur.execute("SELECT schedule_id, seat_code, seat_pk FROM national_rail_seats")
    return {(schedule_id, str(seat_code)): seat_pk for schedule_id, seat_code, seat_pk in cur.fetchall()}


def seed_metro_monthly_passes(cur, user_ids: dict[str, Any]) -> dict[str, Any]:
    """
    Seed optional metro monthly pass data when a JSON file exists.

    Supported filenames:
      - metro_monthly_passes.json
      - monthly_passes.json
    """
    data = load_optional("metro_monthly_passes.json") or load_optional("monthly_passes.json")

    if not data:
        print("  metro_monthly_passes: 0 (optional file not found)")
        return fetch_lookup(cur, "metro_monthly_passes", "pass_code", "pass_id")

    columns = [
        "pass_code",
        "user_id",
        "valid_from",
        "valid_until",
        "price_usd",
        "purchased_at",
    ]

    rows = []
    for item in data:
        rows.append(
            (
                item.get("pass_id"),
                require_mapping(user_ids, item.get("user_id"), "monthly pass user_id"),
                item.get("valid_from"),
                item.get("valid_until"),
                item.get("price_usd"),
                item.get("purchased_at"),
            )
        )

    count = insert_many(cur, "metro_monthly_passes", columns, rows)
    print(f"  metro_monthly_passes: {count}")
    return fetch_lookup(cur, "metro_monthly_passes", "pass_code", "pass_id")


def seed_metro_monthly_pass_payments(
    cur,
    monthly_pass_ids: dict[str, Any],
) -> int:
    """
    Seed optional metro monthly pass payment data when a JSON file exists.

    Supported filenames:
      - metro_monthly_pass_payments.json
      - monthly_pass_payments.json

    Expected JSON fields:
      - payment_id: source payment code, e.g. MPP001
      - pass_id / monthly_pass_id / metro_monthly_pass_id: source monthly pass code
      - amount_usd, method, status, paid_at
    """
    data = load_optional("metro_monthly_pass_payments.json") or load_optional("monthly_pass_payments.json")

    if not data:
        print("  metro_monthly_pass_payments: 0 (optional file not found)")
        return 0

    columns = [
        "payment_code",
        "pass_id",
        "amount_usd",
        "method",
        "status",
        "paid_at",
    ]

    rows = []
    for item in data:
        pass_code = (
            item.get("pass_id")
            or item.get("monthly_pass_id")
            or item.get("metro_monthly_pass_id")
        )

        rows.append(
            (
                item.get("payment_id"),
                require_mapping(monthly_pass_ids, pass_code, "monthly pass payment pass_id"),
                item.get("amount_usd"),
                item.get("method"),
                item.get("status"),
                item.get("paid_at"),
            )
        )

    count = insert_many(cur, "metro_monthly_pass_payments", columns, rows)
    print(f"  metro_monthly_pass_payments: {count}")
    return count


def seed_national_rail_bookings(
    cur,
    user_ids: dict[str, Any],
    rail_schedule_ids: dict[str, int],
    rail_station_ids: dict[str, int],
    rail_seat_ids: dict[tuple[int, str], int],
) -> dict[str, Any]:
    data = load("bookings.json")

    columns = [
        "booking_code",
        "user_id",
        "schedule_id",
        "origin_station_id",
        "destination_station_id",
        "travel_date",
        "departure_time",
        "ticket_type",
        "fare_class",
        "coach",
        "seat_pk",
        "stops_travelled",
        "amount_usd",
        "status",
        "booked_at",
        "travelled_at",
    ]

    rows = []
    for item in data:
        schedule_pk = require_mapping(rail_schedule_ids, item.get("schedule_id"), "booking schedule_id")
        seat_code = str(item.get("seat_id"))

        seat_key = (schedule_pk, seat_code)
        if seat_key not in rail_seat_ids:
            raise ValueError(f"Cannot resolve booking seat: schedule={item.get('schedule_id')}, seat={seat_code}")

        rows.append(
            (
                item.get("booking_id"),
                require_mapping(user_ids, item.get("user_id"), "booking user_id"),
                schedule_pk,
                require_mapping(rail_station_ids, item.get("origin_station_id"), "booking origin_station_id"),
                require_mapping(rail_station_ids, item.get("destination_station_id"), "booking destination_station_id"),
                item.get("travel_date"),
                item.get("departure_time"),
                item.get("ticket_type"),
                item.get("fare_class"),
                item.get("coach"),
                rail_seat_ids[seat_key],
                item.get("stops_travelled"),
                item.get("amount_usd"),
                item.get("status"),
                item.get("booked_at"),
                item.get("travelled_at"),
            )
        )

    count = insert_many(cur, "national_rail_bookings", columns, rows)
    print(f"  national_rail_bookings: {count}")
    return fetch_lookup(cur, "national_rail_bookings", "booking_code", "booking_id")


def seed_metro_trips(
    cur,
    user_ids: dict[str, Any],
    metro_schedule_ids: dict[str, int],
    metro_station_ids: dict[str, int],
    monthly_pass_ids: dict[str, Any],
) -> dict[str, Any]:
    data = load("metro_travel_history.json")

    columns = [
        "trip_code",
        "user_id",
        "schedule_id",
        "origin_station_id",
        "destination_station_id",
        "travel_date",
        "ticket_type",
        "day_pass_ref",
        "monthly_pass_ref",
        "stops_travelled",
        "amount_usd",
        "status",
        "purchased_at",
        "travelled_at",
    ]

    # First insert with day_pass_ref = NULL because it references metro_trips itself.
    rows = []
    pending_day_pass_refs: list[tuple[str, str]] = []

    for item in data:
        monthly_pass_ref = None
        monthly_pass_code = item.get("monthly_pass_ref")
        if monthly_pass_code:
            monthly_pass_ref = require_mapping(monthly_pass_ids, monthly_pass_code, "metro trip monthly_pass_ref")

        day_pass_code = item.get("day_pass_ref")
        if day_pass_code:
            pending_day_pass_refs.append((str(item.get("trip_id")), str(day_pass_code)))

        rows.append(
            (
                item.get("trip_id"),
                require_mapping(user_ids, item.get("user_id"), "metro trip user_id"),
                require_mapping(metro_schedule_ids, item.get("schedule_id"), "metro trip schedule_id"),
                require_mapping(metro_station_ids, item.get("origin_station_id"), "metro trip origin_station_id"),
                require_mapping(metro_station_ids, item.get("destination_station_id"), "metro trip destination_station_id"),
                item.get("travel_date"),
                item.get("ticket_type"),
                None,
                monthly_pass_ref,
                item.get("stops_travelled"),
                item.get("amount_usd"),
                item.get("status"),
                item.get("purchased_at"),
                item.get("travelled_at"),
            )
        )

    count = insert_many(cur, "metro_trips", columns, rows)
    print(f"  metro_trips: {count}")

    trip_ids = fetch_lookup(cur, "metro_trips", "trip_code", "trip_id")

    for trip_code, day_pass_code in pending_day_pass_refs:
        cur.execute(
            """
            UPDATE metro_trips
            SET day_pass_ref = %s
            WHERE trip_code = %s
              AND day_pass_ref IS NULL
            """,
            (
                require_mapping(trip_ids, day_pass_code, "metro trip day_pass_ref"),
                trip_code,
            ),
        )

    if pending_day_pass_refs:
        print(f"  metro_trips day_pass_ref updated: {len(pending_day_pass_refs)}")

    return trip_ids


def seed_payments(
    cur,
    booking_ids: dict[str, Any],
    trip_ids: dict[str, Any],
) -> int:
    """
    Split payments.json into:
      - national_rail_payments when booking_id starts with BK
      - metro_payments when booking_id starts with MT
    """
    data = load("payments.json")

    rail_columns = [
        "payment_code",
        "booking_id",
        "amount_usd",
        "method",
        "status",
        "paid_at",
    ]

    metro_columns = [
        "payment_code",
        "trip_id",
        "amount_usd",
        "method",
        "status",
        "paid_at",
    ]

    rail_rows = []
    metro_rows = []

    for item in data:
        transaction_code = require_prefix(
            item.get("booking_id"),
            ("BK", "MT"),
            f"payment_id={item.get('payment_id')}",
        )

        if transaction_code.startswith("BK"):
            rail_rows.append(
                (
                    item.get("payment_id"),
                    require_mapping(booking_ids, transaction_code, "payment booking_id"),
                    item.get("amount_usd"),
                    item.get("method"),
                    item.get("status"),
                    item.get("paid_at"),
                )
            )
        else:
            metro_rows.append(
                (
                    item.get("payment_id"),
                    require_mapping(trip_ids, transaction_code, "payment trip_id"),
                    item.get("amount_usd"),
                    item.get("method"),
                    item.get("status"),
                    item.get("paid_at"),
                )
            )

    rail_count = insert_many(cur, "national_rail_payments", rail_columns, rail_rows)
    metro_count = insert_many(cur, "metro_payments", metro_columns, metro_rows)

    print(f"  national_rail_payments: {rail_count}")
    print(f"  metro_payments: {metro_count}")

    return rail_count + metro_count


def update_loyalty_points(cur) -> None:
    """
    Recalculate loyalty points from paid rail, metro trip, and monthly pass transactions.

    Rule used here:
      points = FLOOR(amount_usd * 10) for each paid transaction
      only completed/confirmed rail bookings, completed metro trips,
      and paid monthly pass purchases count
    """
    cur.execute("""
        UPDATE registered_users
        SET loyalty_points = 0;
    """)

    cur.execute("""
        UPDATE registered_users u
        SET loyalty_points = p.points
        FROM (
            SELECT
                user_id,
                SUM(points)::int AS points
            FROM (
                SELECT
                    b.user_id,
                    FLOOR(np.amount_usd * 10)::int AS points
                FROM national_rail_bookings b
                JOIN national_rail_payments np
                  ON np.booking_id = b.booking_id
                WHERE b.status IN ('confirmed', 'completed')
                  AND np.status = 'paid'

                UNION ALL

                SELECT
                    t.user_id,
                    FLOOR(mp.amount_usd * 10)::int AS points
                FROM metro_trips t
                JOIN metro_payments mp
                  ON mp.trip_id = t.trip_id
                WHERE t.status = 'completed'
                  AND mp.status = 'paid'

                UNION ALL

                SELECT
                    p.user_id,
                    FLOOR(mpp.amount_usd * 10)::int AS points
                FROM metro_monthly_passes p
                JOIN metro_monthly_pass_payments mpp
                  ON mpp.pass_id = p.pass_id
                WHERE mpp.status = 'paid'
            ) all_points
            GROUP BY user_id
        ) p
        WHERE u.user_id = p.user_id;
    """)
    print("  loyalty_points recalculated")


def seed_feedback(
    cur,
    user_ids: dict[str, Any],
    booking_ids: dict[str, Any],
    trip_ids: dict[str, Any],
) -> int:
    """
    Split feedback.json into:
      - national_rail_feedback when booking_id starts with BK
      - metro_feedback when booking_id starts with MT
    """
    data = load("feedback.json")

    rail_columns = [
        "feedback_code",
        "booking_id",
        "user_id",
        "rating",
        "comment",
        "submitted_at",
    ]

    metro_columns = [
        "feedback_code",
        "trip_id",
        "user_id",
        "rating",
        "comment",
        "submitted_at",
    ]

    rail_rows = []
    metro_rows = []

    for item in data:
        transaction_code = require_prefix(
            item.get("booking_id"),
            ("BK", "MT"),
            f"feedback_id={item.get('feedback_id')}",
        )

        if transaction_code.startswith("BK"):
            rail_rows.append(
                (
                    item.get("feedback_id"),
                    require_mapping(booking_ids, transaction_code, "feedback booking_id"),
                    require_mapping(user_ids, item.get("user_id"), "feedback user_id"),
                    item.get("rating"),
                    item.get("comment"),
                    item.get("submitted_at"),
                )
            )
        else:
            metro_rows.append(
                (
                    item.get("feedback_id"),
                    require_mapping(trip_ids, transaction_code, "feedback trip_id"),
                    require_mapping(user_ids, item.get("user_id"), "feedback user_id"),
                    item.get("rating"),
                    item.get("comment"),
                    item.get("submitted_at"),
                )
            )

    rail_count = insert_many(cur, "national_rail_feedback", rail_columns, rail_rows)
    metro_count = insert_many(cur, "metro_feedback", metro_columns, metro_rows)

    print(f"  national_rail_feedback: {rail_count}")
    print(f"  metro_feedback: {metro_count}")

    return rail_count + metro_count


def print_summary(cur) -> None:
    """Print table counts after seeding."""
    tables = [
        "registered_users",
        "national_rail_stations",
        "metro_stations",
        "national_rail_schedules",
        "national_rail_schedule_stops",
        "metro_schedules",
        "metro_schedule_stops",
        "metro_platforms",
        "national_rail_platforms",
        "national_rail_seats",
        "metro_monthly_passes",
        "metro_monthly_pass_payments",
        "national_rail_bookings",
        "metro_trips",
        "national_rail_payments",
        "metro_payments",
        "national_rail_feedback",
        "metro_feedback",
    ]

    print("\nCurrent table counts:")
    for table in tables:
        cur.execute(sql.SQL("SELECT COUNT(*) FROM {}").format(sql.Identifier(table)))
        count = cur.fetchone()[0]
        print(f"  {table}: {count}")


# ── main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    print("Connecting to PostgreSQL...")
    conn = connect()
    conn.autocommit = False
    cur = conn.cursor()

    try:
        print("Seeding tables (dependency order):")

        # 1. Independent master data.
        user_ids = seed_users(cur)
        metro_station_ids = seed_metro_stations(cur)
        rail_station_ids = seed_national_rail_stations(cur)
        update_station_interchanges(cur)

        # 2. Schedules and normalized schedule stops.
        metro_schedule_ids = seed_metro_schedules(cur, metro_station_ids)
        rail_schedule_ids = seed_national_rail_schedules(cur, rail_station_ids)

        # 3. Schedule children.
        seed_metro_platforms(cur, metro_schedule_ids, metro_station_ids)
        seed_national_rail_platforms(cur, rail_schedule_ids, rail_station_ids)
        rail_seat_ids = seed_national_rail_seats(cur, rail_schedule_ids)

        # 4. Users' transactions.
        monthly_pass_ids = seed_metro_monthly_passes(cur, user_ids)
        seed_metro_monthly_pass_payments(cur, monthly_pass_ids)
        booking_ids = seed_national_rail_bookings(
            cur,
            user_ids,
            rail_schedule_ids,
            rail_station_ids,
            rail_seat_ids,
        )
        trip_ids = seed_metro_trips(
            cur,
            user_ids,
            metro_schedule_ids,
            metro_station_ids,
            monthly_pass_ids,
        )

        # 5. Split payments and feedback.
        seed_payments(cur, booking_ids, trip_ids)
        seed_feedback(cur, user_ids, booking_ids, trip_ids)
        update_loyalty_points(cur)

        print_summary(cur)

        conn.commit()
        print("\nAll done. Database seeded successfully.")

    except Exception as e:
        conn.rollback()
        print(f"\nError: {e}")
        raise

    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    main()
