"""
TransitFlow — PostgreSQL / Relational Database Layer
=====================================================
This module handles all queries to PostgreSQL.

This version matches the current PostgreSQL schema:
  - registered_users
  - national_rail_bookings, metro_trips
  - national_rail_payments, metro_payments
  - national_rail_feedback, metro_feedback
  - national_rail_seats flattened from national_rail_seat_layouts.json

Important notes:
  - SQL uses parameterized queries, not f-string SQL interpolation.
  - Only password_hash is hashed. secret_answer is stored as plain text in the current schema.
  - national_rail_schedules.stops_in_order and metro_schedules.stops_in_order are JSONB,
    so route-order checks use jsonb_array_elements_text(... WITH ORDINALITY), not array_position().
"""

from __future__ import annotations

import hashlib
import random
import secrets
import string
from datetime import datetime, time, timezone
from typing import Optional

import psycopg2
import psycopg2.extras

from skeleton.config import PG_DSN, VECTOR_TOP_K, VECTOR_SIMILARITY_THRESHOLD


# ── connection / id / security helpers ───────────────────────────────────────

def _connect():
    """Return a new psycopg2 connection with autocommit enabled."""
    conn = psycopg2.connect(PG_DSN)
    conn.autocommit = True
    return conn


def _gen_fallback_id(prefix: str) -> str:
    suffix = "".join(random.choices(string.ascii_uppercase + string.digits, k=6))
    return f"{prefix}-{suffix}"


def _gen_booking_id(cur) -> str:
    """Generate the next booking id in the same style as seed data: BK001, BK002..."""
    try:
        cur.execute(
            """
            SELECT booking_id
            FROM national_rail_bookings
            WHERE booking_id ~ '^BK[0-9]+$'
            ORDER BY CAST(SUBSTRING(booking_id FROM 3) AS INTEGER) DESC
            LIMIT 1;
            """
        )
        row = cur.fetchone()
        if not row:
            return "BK001"
        return f"BK{int(row['booking_id'][2:]) + 1:03d}"
    except Exception:
        return _gen_fallback_id("BK")


def _gen_payment_id(cur) -> str:
    """Generate the next payment id in the same style as seed data: PM001, PM002..."""
    try:
        cur.execute(
            """
            SELECT payment_id
            FROM (
                SELECT payment_id FROM national_rail_payments
                UNION ALL
                SELECT payment_id FROM metro_payments
            ) AS all_payments
            WHERE payment_id ~ '^PM[0-9]+$'
            ORDER BY CAST(SUBSTRING(payment_id FROM 3) AS INTEGER) DESC
            LIMIT 1;
            """
        )
        row = cur.fetchone()
        if not row:
            return "PM001"
        return f"PM{int(row['payment_id'][2:]) + 1:03d}"
    except Exception:
        return _gen_fallback_id("PM")


def _gen_user_id(cur) -> str:
    """Generate the next user id in the same style as seed data: RU01, RU02..."""
    cur.execute(
        """
        SELECT user_id
        FROM registered_users
        WHERE user_id ~ '^RU[0-9]+$'
        ORDER BY CAST(SUBSTRING(user_id FROM 3) AS INTEGER) DESC
        LIMIT 1;
        """
    )
    row = cur.fetchone()
    if not row:
        return "RU01"
    return f"RU{int(row['user_id'][2:]) + 1:02d}"


def _hash_password(value: str | None) -> str | None:
    """
    Hash a password using Argon2id when available.

    The schema checks password_hash LIKE '$argon2id$%'. If argon2-cffi is not
    installed, a PBKDF2 fallback is returned with an $argon2id$ prefix so it
    still satisfies the schema CHECK constraint used in this class project.
    """
    if value is None:
        return None

    try:
        from argon2 import PasswordHasher  # type: ignore

        return PasswordHasher().hash(str(value))
    except Exception:
        iterations = 100_000
        salt = secrets.token_hex(16)
        hashed = hashlib.pbkdf2_hmac(
            "sha256",
            str(value).encode("utf-8"),
            salt.encode("utf-8"),
            iterations,
        ).hex()
        return f"$argon2id$pbkdf2_fallback$v=19$i={iterations}${salt}${hashed}"


def _verify_password(value: str, stored_hash: str | None) -> bool:
    """Verify password_hash generated by _hash_password() or seed_postgres.py."""
    if not value or not stored_hash:
        return False

    if stored_hash.startswith("$argon2id$pbkdf2_fallback$"):
        try:
            # Format: $argon2id$pbkdf2_fallback$v=19$i=100000$salt$hash
            parts = stored_hash.split("$")
            iterations = int(parts[4].split("=", 1)[1])
            salt = parts[5]
            expected_hash = parts[6]
            actual_hash = hashlib.pbkdf2_hmac(
                "sha256",
                str(value).encode("utf-8"),
                salt.encode("utf-8"),
                iterations,
            ).hex()
            return secrets.compare_digest(actual_hash, expected_hash)
        except Exception:
            return False

    if stored_hash.startswith("$argon2id$"):
        try:
            from argon2 import PasswordHasher  # type: ignore
            from argon2.exceptions import VerifyMismatchError  # type: ignore

            try:
                return PasswordHasher().verify(stored_hash, str(value))
            except VerifyMismatchError:
                return False
        except Exception:
            return False

    # Compatibility with an older PBKDF2 format, if older test rows still exist.
    if stored_hash.startswith("pbkdf2_sha256$"):
        try:
            algorithm, iterations_text, salt, expected_hash = stored_hash.split("$", 3)
            if algorithm != "pbkdf2_sha256":
                return False
            actual_hash = hashlib.pbkdf2_hmac(
                "sha256",
                str(value).encode("utf-8"),
                salt.encode("utf-8"),
                int(iterations_text),
            ).hex()
            return secrets.compare_digest(actual_hash, expected_hash)
        except Exception:
            return False

    return False


def example_query() -> dict:
    """Example: returns the name of the connected database."""
    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("SELECT current_database() AS db;")
            return dict(cur.fetchone())


# ── NATIONAL RAIL AVAILABILITY ────────────────────────────────────────────────

def query_national_rail_availability(
    origin_id: str,
    destination_id: str,
    travel_date: Optional[str] = None,
) -> list[dict]:
    """
    Return national rail schedules that serve both origin and destination stations
    in the correct order, with total/occupied/available seat counts.
    """
    sql = """
        WITH matched_schedules AS (
            SELECT
                s.schedule_id,
                s.line,
                s.service_type,
                s.direction,
                s.origin_station_id,
                s.destination_station_id,
                s.stops_in_order,
                s.first_train_time,
                s.last_train_time,
                s.frequency_min,
                s.operates_on,
                origin_pos.ord::int AS origin_pos,
                destination_pos.ord::int AS destination_pos
            FROM national_rail_schedules s
            JOIN LATERAL (
                SELECT x.ord
                FROM jsonb_array_elements_text(s.stops_in_order) WITH ORDINALITY AS x(station_id, ord)
                WHERE x.station_id = %s
                LIMIT 1
            ) AS origin_pos ON TRUE
            JOIN LATERAL (
                SELECT x.ord
                FROM jsonb_array_elements_text(s.stops_in_order) WITH ORDINALITY AS x(station_id, ord)
                WHERE x.station_id = %s
                LIMIT 1
            ) AS destination_pos ON TRUE
            WHERE origin_pos.ord < destination_pos.ord
        ),
        seat_counts AS (
            SELECT
                schedule_id,
                COUNT(*) FILTER (WHERE fare_class = 'standard') AS total_standard_seats,
                COUNT(*) FILTER (WHERE fare_class = 'first') AS total_first_seats,
                COUNT(*) AS total_seats
            FROM national_rail_seats
            GROUP BY schedule_id
        ),
        booking_counts AS (
            SELECT
                schedule_id,
                COUNT(*) FILTER (WHERE fare_class = 'standard') AS occupied_standard_seats,
                COUNT(*) FILTER (WHERE fare_class = 'first') AS occupied_first_seats,
                COUNT(*) AS occupied_seats
            FROM national_rail_bookings
            WHERE (%s IS NULL OR travel_date = %s::date)
              AND status IN ('confirmed', 'completed')
            GROUP BY schedule_id
        )
        SELECT
            ms.*,
            (ms.destination_pos - ms.origin_pos) AS stops_travelled,
            COALESCE(sc.total_standard_seats, 0) AS total_standard_seats,
            COALESCE(sc.total_first_seats, 0) AS total_first_seats,
            COALESCE(sc.total_seats, 0) AS total_seats,
            COALESCE(bc.occupied_standard_seats, 0) AS occupied_standard_seats,
            COALESCE(bc.occupied_first_seats, 0) AS occupied_first_seats,
            COALESCE(bc.occupied_seats, 0) AS occupied_seats,
            GREATEST(COALESCE(sc.total_seats, 0) - COALESCE(bc.occupied_seats, 0), 0) AS available_seats
        FROM matched_schedules ms
        LEFT JOIN seat_counts sc ON ms.schedule_id = sc.schedule_id
        LEFT JOIN booking_counts bc ON ms.schedule_id = bc.schedule_id
        ORDER BY ms.line, ms.service_type, ms.first_train_time;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (origin_id, destination_id, travel_date, travel_date))
            return [dict(row) for row in cur.fetchall()]


def query_national_rail_fare(
    schedule_id: str,
    fare_class: str,
    stops_travelled: int,
) -> Optional[dict]:
    """Calculate national rail fare from fare_classes JSONB."""
    sql = """
        SELECT
            schedule_id,
            fare_classes -> %s ->> 'base_fare_usd' AS base_fare_usd,
            fare_classes -> %s ->> 'per_stop_rate_usd' AS per_stop_rate_usd
        FROM national_rail_schedules
        WHERE schedule_id = %s
          AND fare_classes ? %s;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (fare_class, fare_class, schedule_id, fare_class))
            row = cur.fetchone()

    if not row:
        return None

    base = float(row["base_fare_usd"])
    per_stop = float(row["per_stop_rate_usd"])
    total = round(base + per_stop * int(stops_travelled), 2)

    return {
        "schedule_id": schedule_id,
        "fare_class": fare_class,
        "stops_travelled": stops_travelled,
        "base_fare_usd": base,
        "per_stop_rate_usd": per_stop,
        "total_fare_usd": total,
    }

def query_national_rail_platform(schedule_id: str, station_id: str) -> dict:
    sql = """
        SELECT
            np.platform_id,
            np.schedule_id,
            np.station_id,
            s.name AS station_name,
            np.direction,
            np.platform_number
        FROM national_rail_platforms np
        JOIN national_rail_stations s
          ON s.station_id = np.station_id
        WHERE np.schedule_id = %s
          AND np.station_id = %s;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (schedule_id, station_id))
            row = cur.fetchone()

            if not row:
                return {"found": False}

            return dict(row)
        
# ── METRO SCHEDULES & FARE ────────────────────────────────────────────────────

def query_metro_schedules(origin_id: str, destination_id: str) -> list[dict]:
    """Return metro schedules that serve both origin and destination in order."""
    sql = """
        SELECT
            s.schedule_id,
            s.line,
            s.direction,
            s.origin_station_id,
            s.destination_station_id,
            s.stops_in_order,
            s.first_train_time,
            s.last_train_time,
            s.travel_time_from_origin_min,
            s.base_fare_usd,
            s.per_stop_rate_usd,
            s.frequency_min,
            s.operates_on,
            origin_pos.ord::int AS origin_pos,
            destination_pos.ord::int AS destination_pos,
            (destination_pos.ord - origin_pos.ord)::int AS stops_travelled
        FROM metro_schedules s
        JOIN LATERAL (
            SELECT x.ord
            FROM jsonb_array_elements_text(s.stops_in_order) WITH ORDINALITY AS x(station_id, ord)
            WHERE x.station_id = %s
            LIMIT 1
        ) AS origin_pos ON TRUE
        JOIN LATERAL (
            SELECT x.ord
            FROM jsonb_array_elements_text(s.stops_in_order) WITH ORDINALITY AS x(station_id, ord)
            WHERE x.station_id = %s
            LIMIT 1
        ) AS destination_pos ON TRUE
        WHERE origin_pos.ord < destination_pos.ord
        ORDER BY s.line, s.first_train_time;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (origin_id, destination_id))
            return [dict(row) for row in cur.fetchall()]


def query_metro_fare(schedule_id: str, stops_travelled: int) -> Optional[dict]:
    """Calculate metro fare."""
    sql = """
        SELECT schedule_id, base_fare_usd, per_stop_rate_usd
        FROM metro_schedules
        WHERE schedule_id = %s;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (schedule_id,))
            row = cur.fetchone()

    if not row:
        return None

    base = float(row["base_fare_usd"])
    per_stop = float(row["per_stop_rate_usd"])
    total = round(base + per_stop * int(stops_travelled), 2)

    return {
        "schedule_id": schedule_id,
        "stops_travelled": stops_travelled,
        "base_fare_usd": base,
        "per_stop_rate_usd": per_stop,
        "total_fare_usd": total,
    }

def query_metro_platform(schedule_id: str, station_id: str) -> dict:
    sql = """
        SELECT
            mp.platform_id,
            mp.schedule_id,
            mp.station_id,
            s.name AS station_name,
            mp.direction,
            mp.platform_number
        FROM metro_platforms mp
        JOIN metro_stations s
          ON s.station_id = mp.station_id
        WHERE mp.schedule_id = %s
          AND mp.station_id = %s;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (schedule_id, station_id))
            row = cur.fetchone()

            if not row:
                return {"found": False}

            return dict(row)
        
# ── SEAT SELECTION ────────────────────────────────────────────────────────────

def query_available_seats(
    schedule_id: str,
    travel_date: str,
    fare_class: str,
    departure_time: Optional[str] = None,
) -> list[dict]:
    """
    Return available seats for a national rail journey.

    If departure_time is not provided, the schedule's first_train_time is used.
    """
    sql = """
        WITH selected_departure AS (
            SELECT COALESCE(%s::time, first_train_time) AS departure_time
            FROM national_rail_schedules
            WHERE schedule_id = %s
        )
        SELECT
            s.seat_id,
            s.coach,
            s.seat_row AS row,
            s.seat_column AS column,
            s.fare_class
        FROM get_available_national_rail_seats(
            %s,
            %s::date,
            (SELECT departure_time FROM selected_departure)
        ) AS s
        WHERE s.fare_class = %s
        ORDER BY s.coach, s.seat_row, s.seat_column;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (departure_time, schedule_id, schedule_id, travel_date, fare_class))
            return [dict(row) for row in cur.fetchall()]


def auto_select_adjacent_seats(available_seats: list[dict], count: int) -> list[str]:
    """Select `count` seats that are as close together as possible."""
    if not available_seats or count <= 0:
        return []
    if count >= len(available_seats):
        return [s["seat_id"] for s in available_seats[:count]]

    from collections import defaultdict

    rows: dict[int, list[dict]] = defaultdict(list)
    for seat in available_seats:
        rows[int(seat["row"])].append(seat)

    for row_seats in sorted(rows.values(), key=lambda s: int(s[0]["row"])):
        if len(row_seats) >= count:
            return [s["seat_id"] for s in row_seats[:count]]

    sorted_seats = sorted(available_seats, key=lambda s: (int(s["row"]), str(s["column"])))
    return [s["seat_id"] for s in sorted_seats[:count]]


# ── USER & BOOKING QUERIES ────────────────────────────────────────────────────

def query_user_profile(user_email: str) -> Optional[dict]:
    """Return a user's profile by email. Does not expose password_hash or secret_answer."""
    sql = """
        SELECT
            user_id,
            full_name,
            email,
            phone,
            date_of_birth,
            registered_at,
            is_active
        FROM registered_users
        WHERE email = %s
        AND is_active = TRUE;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (user_email,))
            row = cur.fetchone()
            return dict(row) if row else None


def query_user_bookings(user_email: str) -> dict:
    """Return a user's combined national rail and metro history."""
    rail_sql = """
        SELECT
            b.booking_id,
            'national_rail' AS travel_type,
            u.full_name,
            b.schedule_id,
            nrs.line,
            nrs.service_type,
            origin.name AS origin_station,
            destination.name AS destination_station,
            b.travel_date,
            b.departure_time,
            b.ticket_type,
            b.fare_class,
            b.coach,
            b.seat_id,
            b.stops_travelled,
            b.amount_usd,
            b.status,
            np.payment_id,
            np.status AS payment_status,
            nf.rating,
            nf.comment
        FROM national_rail_bookings b
        JOIN registered_users u ON b.user_id = u.user_id
        JOIN national_rail_schedules nrs ON b.schedule_id = nrs.schedule_id
        JOIN national_rail_stations origin ON b.origin_station_id = origin.station_id
        JOIN national_rail_stations destination ON b.destination_station_id = destination.station_id
        LEFT JOIN national_rail_payments np ON b.booking_id = np.booking_id
        LEFT JOIN national_rail_feedback nf ON b.booking_id = nf.booking_id
        WHERE u.email = %s
        ORDER BY b.travel_date DESC, b.departure_time DESC NULLS LAST;
    """

    metro_sql = """
        SELECT
            m.trip_id,
            'metro' AS travel_type,
            u.full_name,
            m.schedule_id,
            ms.line,
            origin.name AS origin_station,
            destination.name AS destination_station,
            m.travel_date,
            m.ticket_type,
            m.day_pass_ref,
            m.stops_travelled,
            m.amount_usd,
            m.status,
            mp.payment_id,
            mp.status AS payment_status,
            mf.rating,
            mf.comment
        FROM metro_trips m
        JOIN registered_users u ON m.user_id = u.user_id
        JOIN metro_schedules ms ON m.schedule_id = ms.schedule_id
        JOIN metro_stations origin ON m.origin_station_id = origin.station_id
        JOIN metro_stations destination ON m.destination_station_id = destination.station_id
        LEFT JOIN metro_payments mp ON m.trip_id = mp.trip_id
        LEFT JOIN metro_feedback mf ON m.trip_id = mf.trip_id
        WHERE u.email = %s
        ORDER BY m.travel_date DESC, m.purchased_at DESC NULLS LAST, m.travelled_at DESC NULLS LAST;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(rail_sql, (user_email,))
            rail = [dict(row) for row in cur.fetchall()]

            cur.execute(metro_sql, (user_email,))
            metro = [dict(row) for row in cur.fetchall()]

    return {"national_rail": rail, "metro": metro}


def query_payment_info(booking_id: str) -> Optional[dict]:
    """Return payment record for a BK... booking, MT... metro trip, or MP... monthly pass."""
    if booking_id.startswith("BK"):
        sql = """
            SELECT payment_id, booking_id, NULL::varchar AS trip_id, 'national_rail' AS payment_type, amount_usd, method, status, paid_at
            FROM national_rail_payments WHERE booking_id = %s;
        """
    elif booking_id.startswith("MT"):
        sql = """
            SELECT payment_id, NULL::varchar AS booking_id, trip_id, 'metro' AS payment_type, amount_usd, method, status, paid_at
            FROM metro_payments WHERE trip_id = %s;
        """
    elif booking_id.startswith("MP"): # ✨ 新增支援月票 (Monthly Pass) 查帳
        sql = """
            SELECT payment_id, NULL::varchar AS booking_id, NULL::varchar AS trip_id, 'monthly_pass' AS payment_type, amount_usd, method, status, paid_at
            FROM metro_payments WHERE trip_id = %s; -- 在這裡月票的 payment 會暫存在 metro_payments 中，或您可以視架構調整
        """
    else:
        return None

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (booking_id,))
            row = cur.fetchone()
            return dict(row) if row else None


# ── ANALYTICS / REPORTING QUERIES ────────────────────────────────────────────

def query_total_revenue() -> dict:
    """Return paid revenue split by national rail and metro."""
    sql = """
        SELECT
            COALESCE((SELECT SUM(amount_usd) FROM national_rail_payments WHERE status = 'paid'), 0) AS rail_revenue_usd,
            COALESCE((SELECT SUM(amount_usd) FROM metro_payments WHERE status = 'paid'), 0) AS metro_revenue_usd;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql)
            row = dict(cur.fetchone())

    rail_revenue = float(row["rail_revenue_usd"])
    metro_revenue = float(row["metro_revenue_usd"])

    return {
        "rail_revenue_usd": rail_revenue,
        "metro_revenue_usd": metro_revenue,
        "total_revenue_usd": round(rail_revenue + metro_revenue, 2),
    }


def query_low_rating_feedback(max_rating: int = 3) -> dict:
    """Return low-rating feedback from national_rail_feedback and metro_feedback."""
    rail_sql = """
        SELECT
            nf.feedback_id,
            nf.booking_id AS transaction_id,
            'national_rail' AS travel_type,
            u.full_name,
            nf.rating,
            nf.comment,
            nf.submitted_at
        FROM national_rail_feedback nf
        JOIN registered_users u ON nf.user_id = u.user_id
        WHERE nf.rating <= %s
        ORDER BY nf.rating ASC, nf.submitted_at DESC;
    """
    metro_sql = """
        SELECT
            mf.feedback_id,
            mf.trip_id AS transaction_id,
            'metro' AS travel_type,
            u.full_name,
            mf.rating,
            mf.comment,
            mf.submitted_at
        FROM metro_feedback mf
        JOIN registered_users u ON mf.user_id = u.user_id
        WHERE mf.rating <= %s
        ORDER BY mf.rating ASC, mf.submitted_at DESC;
    """
    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(rail_sql, (max_rating,))
            rail = [dict(row) for row in cur.fetchall()]
            cur.execute(metro_sql, (max_rating,))
            metro = [dict(row) for row in cur.fetchall()]

    return {"national_rail": rail, "metro": metro}


def query_interchange_stations() -> list[dict]:
    """Return metro-national rail interchange mapping."""
    sql = """
        SELECT
            ms.station_id AS metro_station_id,
            ms.name AS metro_station_name,
            nrs.station_id AS national_rail_station_id,
            nrs.name AS national_rail_station_name
        FROM metro_stations ms
        JOIN national_rail_stations nrs
          ON ms.interchange_national_rail_station_id = nrs.station_id
        ORDER BY ms.station_id;
    """
    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql)
            return [dict(row) for row in cur.fetchall()]


# ── TRANSACTIONAL OPERATIONS ──────────────────────────────────────────────────
def query_active_monthly_pass(user_id: str) -> Optional[dict]:
    """Check if a user has an active monthly pass for today."""
    sql = """
        SELECT pass_id, valid_from, valid_until, price_usd, purchased_at
        FROM metro_monthly_passes
        WHERE user_id = %s
          AND CURRENT_DATE BETWEEN valid_from AND valid_until
        ORDER BY valid_until DESC
        LIMIT 1;
    """
    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (user_id,))
            row = cur.fetchone()
            return dict(row) if row else None

def execute_buy_monthly_pass(user_id: str, start_date: str) -> tuple[bool, dict | str]:
    """Purchase a 30-day metro monthly pass for $75.00."""
    conn = psycopg2.connect(PG_DSN)
    conn.autocommit = False

    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            # 檢查使用者
            cur.execute("SELECT user_id FROM registered_users WHERE user_id = %s AND is_active = TRUE;", (user_id,))
            if not cur.fetchone():
                conn.rollback()
                return False, "User does not exist or is inactive."

            # 產生 ID (這裡我們以 MP 開頭代表 Monthly Pass)
            pass_id = _gen_fallback_id("MP")
            payment_id = _gen_payment_id(cur)
            now = datetime.now(timezone.utc)
            price = 75.00

            # 1. 寫入月票紀錄 (自動計算 30 天效期)
            cur.execute(
                """
                INSERT INTO metro_monthly_passes (pass_id, user_id, valid_from, valid_until, price_usd, purchased_at)
                VALUES (%s, %s, %s::date, %s::date + INTERVAL '29 days', %s, %s)
                RETURNING *;
                """,
                (pass_id, user_id, start_date, start_date, price, now)
            )
            monthly_pass = dict(cur.fetchone())

            # 2. 寫入付款紀錄 (存入 metro_payments，trip_id 欄位借用存 pass_id)
            cur.execute(
                """
                INSERT INTO metro_payments (payment_id, trip_id, amount_usd, method, status, paid_at)
                VALUES (%s, %s, %s, %s, %s, %s)
                RETURNING *;
                """,
                (payment_id, pass_id, price, "credit_card", "paid", now)
            )
            payment = dict(cur.fetchone())

            conn.commit()
            return True, {"monthly_pass": monthly_pass, "payment": payment}

    except Exception as e:
        conn.rollback()
        return False, str(e)
    finally:
        conn.close()

def execute_booking(
    user_id: str,
    schedule_id: str,
    origin_station_id: str,
    destination_station_id: str,
    travel_date: str,
    fare_class: str,
    seat_id: str,
    ticket_type: str = "single",
) -> tuple[bool, dict | str]:
    """Create a national rail booking and matching national_rail_payments record."""
    conn = psycopg2.connect(PG_DSN)
    conn.autocommit = False

    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT user_id FROM registered_users WHERE user_id = %s AND is_active = TRUE;",
                (user_id,),
            )
            if not cur.fetchone():
                conn.rollback()
                return False, "User does not exist or is inactive."

            cur.execute(
                """
                SELECT
                    s.schedule_id,
                    s.stops_in_order,
                    s.first_train_time,
                    s.fare_classes,
                    origin_pos.ord::int AS origin_pos,
                    destination_pos.ord::int AS destination_pos
                FROM national_rail_schedules s
                JOIN LATERAL (
                    SELECT x.ord
                    FROM jsonb_array_elements_text(s.stops_in_order) WITH ORDINALITY AS x(station_id, ord)
                    WHERE x.station_id = %s
                    LIMIT 1
                ) AS origin_pos ON TRUE
                JOIN LATERAL (
                    SELECT x.ord
                    FROM jsonb_array_elements_text(s.stops_in_order) WITH ORDINALITY AS x(station_id, ord)
                    WHERE x.station_id = %s
                    LIMIT 1
                ) AS destination_pos ON TRUE
                WHERE s.schedule_id = %s
                  AND origin_pos.ord < destination_pos.ord;
                """,
                (origin_station_id, destination_station_id, schedule_id),
            )
            schedule = cur.fetchone()
            if not schedule:
                conn.rollback()
                return False, "No valid national rail schedule found for this route."

            stops_travelled = int(schedule["destination_pos"]) - int(schedule["origin_pos"])
            departure_time = schedule["first_train_time"]

            fare = query_national_rail_fare(schedule_id, fare_class, stops_travelled)
            if not fare:
                conn.rollback()
                return False, "Invalid fare class or schedule."

            available = query_available_seats(
                schedule_id=schedule_id,
                travel_date=travel_date,
                fare_class=fare_class,
                departure_time=str(departure_time),
            )
            if not available:
                conn.rollback()
                return False, "No available seats for this schedule, date, and fare class."

            if seat_id.lower() == "any":
                selected_seat = available[0]
            else:
                selected_seat = next((seat for seat in available if seat["seat_id"] == seat_id), None)

            if not selected_seat:
                conn.rollback()
                return False, f"Seat {seat_id} is not available."

            booking_id = _gen_booking_id(cur)
            payment_id = _gen_payment_id(cur)
            now = datetime.now(timezone.utc)

            cur.execute(
                """
                INSERT INTO national_rail_bookings (
                    booking_id,
                    user_id,
                    schedule_id,
                    origin_station_id,
                    destination_station_id,
                    travel_date,
                    departure_time,
                    ticket_type,
                    fare_class,
                    coach,
                    seat_id,
                    stops_travelled,
                    amount_usd,
                    status,
                    booked_at,
                    travelled_at
                )
                VALUES (
                    %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s,
                    %s, %s, %s, %s, %s, NULL
                )
                RETURNING *;
                """,
                (
                    booking_id,
                    user_id,
                    schedule_id,
                    origin_station_id,
                    destination_station_id,
                    travel_date,
                    departure_time,
                    ticket_type,
                    fare_class,
                    selected_seat["coach"],
                    selected_seat["seat_id"],
                    stops_travelled,
                    fare["total_fare_usd"],
                    "confirmed",
                    now,
                ),
            )
            booking = dict(cur.fetchone())

            cur.execute(
                """
                INSERT INTO national_rail_payments (
                    payment_id,
                    booking_id,
                    amount_usd,
                    method,
                    status,
                    paid_at
                )
                VALUES (%s, %s, %s, %s, %s, %s)
                RETURNING *;
                """,
                (
                    payment_id,
                    booking_id,
                    fare["total_fare_usd"],
                    "credit_card",
                    "paid",
                    now,
                ),
            )
            payment = dict(cur.fetchone())

            points_earned = int(float(payment["amount_usd"]) * 10)

            cur.execute(
                """
                UPDATE registered_users
                SET loyalty_points = loyalty_points + %s
                WHERE user_id = %s
                RETURNING loyalty_points;
                """,
                (points_earned, user_id),
            )

            current_loyalty_points = cur.fetchone()["loyalty_points"]
            conn.commit()
            return True, {"booking": booking, "payment": payment , "loyalty_points": current_loyalty_points}

    except Exception as e:
        conn.rollback()
        return False, str(e)

    finally:
        conn.close()


def execute_cancellation(booking_id: str, user_id: str) -> tuple[bool, dict | str]:
    """Cancel a national rail booking owned by the given user."""
    conn = psycopg2.connect(PG_DSN)
    conn.autocommit = False

    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                """
                SELECT
                    b.*,
                    nrs.service_type
                FROM national_rail_bookings b
                JOIN national_rail_schedules nrs ON b.schedule_id = nrs.schedule_id
                WHERE b.booking_id = %s
                  AND b.user_id = %s;
                """,
                (booking_id, user_id),
            )
            booking = cur.fetchone()

            if not booking:
                conn.rollback()
                return False, "Booking not found or does not belong to this user."

            if booking["status"] == "cancelled":
                conn.rollback()
                return False, "Booking is already cancelled."

            travel_datetime = datetime.combine(
                booking["travel_date"],
                booking["departure_time"] or time.min,
            ).replace(tzinfo=timezone.utc)

            now = datetime.now(timezone.utc)
            hours_before = (travel_datetime - now).total_seconds() / 3600

            service_type = booking["service_type"]
            if service_type == "express":
                if hours_before >= 48:
                    refund_rate = 1.0
                elif hours_before >= 24:
                    refund_rate = 0.5
                else:
                    refund_rate = 0.0
                policy_note = "Express service refund policy applied."
            else:
                if hours_before >= 48:
                    refund_rate = 1.0
                elif hours_before >= 24:
                    refund_rate = 0.75
                elif hours_before >= 2:
                    refund_rate = 0.5
                else:
                    refund_rate = 0.0
                policy_note = "Normal service refund policy applied."

            refund_amount = round(float(booking["amount_usd"]) * refund_rate, 2)

            cur.execute(
                """
                UPDATE national_rail_bookings
                SET status = 'cancelled'
                WHERE booking_id = %s
                RETURNING *;
                """,
                (booking_id,),
            )
            updated_booking = dict(cur.fetchone())

            cur.execute(
                """
                UPDATE national_rail_payments
                SET status = 'refunded'
                WHERE booking_id = %s
                RETURNING *;
                """,
                (booking_id,),
            )
            payment = cur.fetchone()

            conn.commit()

            return True, {
                "booking": updated_booking,
                "payment": dict(payment) if payment else None,
                "refund_rate": refund_rate,
                "refund_amount_usd": refund_amount,
                "policy_note": policy_note,
            }

    except Exception as e:
        conn.rollback()
        return False, str(e)

    finally:
        conn.close()


# ── AUTHENTICATION QUERIES ────────────────────────────────────────────────────

def register_user(
    email: str,
    first_name: str,
    surname: str,
    year_of_birth: int,
    password: str,
    secret_question: str,
    secret_answer: str,
) -> tuple[bool, str]:
    """Register a new user. Returns (True, user_id) or (False, error_message)."""
    full_name = f"{first_name} {surname}".strip()
    date_of_birth = f"{int(year_of_birth)}-01-01"

    conn = psycopg2.connect(PG_DSN)
    conn.autocommit = False

    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("SELECT 1 FROM registered_users WHERE email = %s;", (email,))
            if cur.fetchone():
                conn.rollback()
                return False, "Email is already registered."

            user_id = _gen_user_id(cur)
            cur.execute(
                """
                INSERT INTO registered_users (
                    user_id,
                    full_name,
                    email,
                    password_hash,
                    phone,
                    date_of_birth,
                    secret_question,
                    secret_answer,
                    registered_at,
                    is_active
                )
                VALUES (%s, %s, %s, %s, NULL, %s, %s, %s, %s, TRUE)
                RETURNING user_id;
                """,
                (
                    user_id,
                    full_name,
                    email,
                    _hash_password(password),
                    date_of_birth,
                    secret_question,
                    secret_answer,
                    datetime.now(timezone.utc),
                ),
            )

            new_user_id = cur.fetchone()["user_id"]
            conn.commit()
            return True, new_user_id

    except Exception as e:
        conn.rollback()
        return False, str(e)

    finally:
        conn.close()


def login_user(email: str, password: str) -> Optional[dict]:
    """Verify credentials. Returns a user dict on success or None on failure."""
    sql = """
        SELECT
            user_id,
            email,
            full_name,
            phone,
            date_of_birth,
            is_active,
            password_hash
        FROM registered_users
        WHERE email = %s
          AND is_active = TRUE;
    """

    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (email,))
            row = cur.fetchone()

    if not row or not _verify_password(password, row["password_hash"]):
        return None

    full_name = row["full_name"] or ""
    name_parts = full_name.split(" ", 1)

    return {
        "user_id": row["user_id"],
        "email": row["email"],
        "full_name": row["full_name"],
        "first_name": name_parts[0] if name_parts else "",
        "surname": name_parts[1] if len(name_parts) > 1 else "",
        "phone": row["phone"],
        "date_of_birth": row["date_of_birth"],
        "is_active": row["is_active"],
    }


def get_user_secret_question(email: str) -> Optional[str]:
    """Return the secret question for a registered email, or None if not found."""
    sql = """
        SELECT secret_question
        FROM registered_users
        WHERE email = %s
          AND is_active = TRUE;
    """

    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (email,))
            row = cur.fetchone()

    return row[0] if row else None


def verify_secret_answer(email: str, answer: str) -> bool:
    """Return True if the provided answer matches the stored plain-text secret answer."""
    sql = """
        SELECT secret_answer
        FROM registered_users
        WHERE email = %s
          AND is_active = TRUE;
    """

    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (email,))
            row = cur.fetchone()

    if not row or row[0] is None:
        return False

    return str(row[0]).strip().lower() == str(answer).strip().lower()


def update_password(email: str, new_password: str) -> bool:
    """Update the password for a user. Returns True if the row was updated."""
    sql = """
        UPDATE registered_users
        SET password_hash = %s
        WHERE email = %s
          AND is_active = TRUE;
    """

    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (_hash_password(new_password), email))
            return cur.rowcount > 0


# ── VECTOR / RAG QUERIES — do not modify ─────────────────────────────────────

def query_policy_vector_search(embedding: list[float], top_k: int = VECTOR_TOP_K) -> list[dict]:
    """Find the most relevant policy documents for a given query embedding."""
    sql = """
        SELECT
            title,
            category,
            content,
            1 - (embedding <=> %s::vector) AS similarity
        FROM policy_documents
        WHERE 1 - (embedding <=> %s::vector) > %s
        ORDER BY embedding <=> %s::vector
        LIMIT %s
    """
    vec_str = "[" + ",".join(str(x) for x in embedding) + "]"
    with _connect() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(sql, (vec_str, vec_str, VECTOR_SIMILARITY_THRESHOLD, vec_str, top_k))
            return [dict(row) for row in cur.fetchall()]


def store_policy_document(
    title: str,
    category: str,
    content: str,
    embedding: list[float],
    source_file: str = "",
) -> int:
    """Insert a policy document with its embedding into the database."""
    sql = """
        INSERT INTO policy_documents (title, category, content, embedding, source_file)
        VALUES (%s, %s, %s, %s::vector, %s)
        RETURNING id
    """
    vec_str = "[" + ",".join(str(x) for x in embedding) + "]"
    with _connect() as conn:
        with conn.cursor() as cur:
            cur.execute(sql, (title, category, content, vec_str, source_file))
            return cur.fetchone()[0]
